### ISSUE TITLE
Is the feed broken? Seems like missing double quotes

### ISSUE THREAD

**Issue by rnons** [philipwalton/blog#44]
![2015-06-08 4 56 34](https://cloud.githubusercontent.com/assets/1082650/8031241/679762aa-0dff-11e5-95e2-f9cdb9985cbf.png)

tested in Firefox and Thunderbird

**Comment by philipwalton** [comment]
Thanks, this should be fixed via f2698748bde1e35a08bf146e323b55e1851b6b74. Let me know if it's still not working.
