### ISSUE TITLE
Consider some updates to deploying-es2015-code-in-production-today.md

### ISSUE THREAD

**Issue by rmacklin** [philipwalton/blog#54]
When I revisited the "Deploying ES2015+ Code in Production Today" article, I was surprised to see it had been updated (inline) to [change `main.js` to `main.mjs`](https://github.com/philipwalton/blog/commit/034fbb1e83944c4770a6dceadb6e4f91b7655f3b#diff-eb398e4aa50a89f7b163cd74cc4bd34c).

Given that this article has been linked from many sites as "_the_ resource" for how to deploy ES2015+ code (e.g. [here](https://github.com/vuejs/vue-cli/blame/3f434f69c6bbff3d6969126544c0bd0128135d33/docs/guide/browser-compatibility.md#L61)), I would suggest explicitly noting that the article has been updated and that the original version of the post didn't use the `.mjs` convention.

Additionally, `.mjs` still has some caveats: it requires you to explicitly set the correct `Content-Type` (because it won't happen automatically, like it does for `.js`, on many popular web servers) and it doesn't generate sourcemaps in webpack (https://github.com/webpack/webpack/issues/7927). Beginners that come to the post are likely to get tripped up by these issues, and they would have avoided them if they read the original version of the post instead. So, I would also suggest clearly calling these issues out. You could perhaps link out to ["A note on file extensions"](https://developers.google.com/web/fundamentals/primers/modules#mjs) and that webpack issue.

**Comment by philipwalton** [comment]
Thanks, this should be addressed by 1e87c67116245cec258245fecc96d3385f6dd76a.

**Comment by philipwalton** [comment]
Update is live: https://philipwalton.com/articles/deploying-es2015-code-in-production-today/#mjs-warnings
