### ISSUE TITLE
https://philipwalton.com/articles/the-google-analytics-setup-i-use-on-every-site-i-build/

### ISSUE THREAD

**Issue by PavanGangireddy** [philipwalton/blog#57]
This link is broken. Cant access in ur blog

**Comment by philipwalton** [comment]
That links works fine for me. I'm going to close this as I assume it's a mistake, but feel free to ping this issue if you're still not able to access this page:
https://philipwalton.com/articles/the-google-analytics-setup-i-use-on-every-site-i-build/

**Comment by radum** [comment]
Its the same for me @philipwalton 

Looks like a SW issue. Once cleared and reloaded works fine but with this error

```
WorkboxError.js:30 Uncaught (in promise) no-response: no-response :: [{"url":"https://philipwalton.com/articles/the-google-analytics-setup-i-use-on-every-site-i-build/index.content.html","error":{}}]
    at Object.handle (https://philipwalton.com/sw.js:1:12243)
    at async Promise.all (index 0)
```

**Comment by Jikodis** [comment]
First visit to that direct link did not work for me oddly enough as well. Searched the URL in Google and came to the issue here. Might be related.
