### ISSUE TITLE
article 'Page Lifecycle API' unload event confused

### ISSUE THREAD

**Issue by fish-404** [philipwalton/blog#68]
Hi, I am new to Web development. I read you artical [Page Lifecycle API | Web | Google Developers](https://developers.google.com/web/updates/2018/07/page-lifecycle-api#legacy-lifecycle-apis-to-avoid), it helps a lot.  I have a little confusion:
In the unload event section, you say:
> If you need to support Internet Explorer versions 10 and lower, you should feature detect the pagehide event and only use unload if the browser doesn't support pagehide:

and you use the code below:
```javascript
const terminationEvent = 'onpagehide' in self ? 'pagehide' : 'unload';
```
I test the code in my project, it seems if we want suprot ie10 and lower, the `const` can't be supported according to [const - Javascirpt | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FStatements%2Fconst#Browser_compatibility), may be we should use `var`? I use `var` successfully in my project. 

And I have another problem, if my project don't need to supprot moblie, will using `unload` directly cause some problems?
Sorry for my poor English. Wish I can be understood. Thanks.

**Comment by philipwalton** [comment]
> I test the code in my project, it seems if we want suprot ie10 and lower, the `const` can't be supported according to [const - Javascirpt | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FStatements%2Fconst#Browser_compatibility), may be we should use `var`? I use `var` successfully in my project.

The assumption is that you're using a transpiler to build the ES5 version of your code, see: https://philipwalton.com/articles/deploying-es2015-code-in-production-today/

> And I have another problem, if my project don't need to supprot moblie, will using `unload` directly cause some problems?

Yes, see: https://web.dev/bfcache/#never-use-the-unload-event
